version: '3'
services:
  node:
    build: .
    ports:
      - ${PORT}:${PORT}
    networks:
      - back
    depends_on:
      - postgres
    environment:
      PORT: ${PORT}
    volumes:
      - ./:/app
    restart: always
  postgres:
    build: ./database/
    networks:
      - back
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data

networks:
  back:
    driver: bridge
volumes:
  pgdata:
