version: '3'
services:
  node:
    build: .
    ports:
      - ${PORT}:${PORT}
    networks:
      - back
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - ./:/app
    restart: always
  db:
    build: ./database/
    networks:
      - back
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    environment:
      POSTGRES_USER: '${POSTGRES_USER}'
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
      POSTGRES_DB: '${POSTGRES_DB}'
      POSTGRES_HOST: '${POSTGRES_HOST}'
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data

networks:
  back:
    driver: bridge
volumes:
  pgdata:
